name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve API Key from AWS Secrets Manager
        id: get_secret
        run: |
          secret=$(aws secretsmanager get-secret-value --secret-id OPENAI_API_KEY --query SecretString --output text)
          echo "REACT_APP_OPENAI_API_KEY=$secret" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          REACT_APP_OPENAI_API_KEY: ${{ env.REACT_APP_OPENAI_API_KEY }}

      - name: Deploy to Amplify
        run: |
          amplify publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
